### PR TITLE
performance tuning

### PR DESCRIPTION
**Pull request by Ahornberg**
added FastTrigo

### CODE REVIEW

**Comment by VegaDeftwing** [comment]
I see FastTrigo depends on `<intrin.h>`,`xmmintrin.h>`, and `pmmintrin.h`. Following the first google result, https://stackoverflow.com/questions/2520683/how-to-cope-with-intrin-h-no-such-file-or-directory, I see this is a MSVC thing, but I'm on Linux and using GCC. I got that working by doing as that answer says and using `#include <x86intrin.h>`, but the performance improvement seems small. I assume you're building on Windows and using MinGW as per the normal plugin dev guide - any idea if you can cross compile for Linux with the MSVC headers? I just want to be sure this doesn't preclude me from getting the Pink Trombone into the library.

**Comment by VegaDeftwing** [comment]
also, I can only assume if we're using intrinstics it will make a pain for anyone wanting to compile for a pi or eventually M1 Apple hardware - so that could be an issue from the start.

**Comment by Ahornberg** [comment]
I removed the dependencies to <intrin.h>, <xmmintrin.h>, <pmmintrin.h> by shrinking down the number of functions provided by FastTrig to only FTA::sin() and FTA::cos().

On my Windows-system PinkTrombone used around 12.5% CPU before my changes, now it uses around 5.5% CPU (indicated by the VCV Rack performance meter).

**Comment by Ahornberg** [comment]
After some tests on different platforms it seems to be clear that the performance improvement only takes place on Windows. On Linux performance does not improve or gets even worse. From my perspective it is better to cancel this pull request.

**Pull request closed without merging**
